# Generated by Django 3.2.6 on 2021-11-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='OrderItem_product',
            new_name='product',
        ),
    ]
