# Generated by Django 3.2.6 on 2021-09-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subsribe',
            new_name='subscribe',
        ),
    ]
