# Generated by Django 3.2.6 on 2021-09-06 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_rename_subsribe_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
