# Generated by Django 3.2.6 on 2021-11-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_title_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
    ]
